mqtt:
  host: "beanie.local"
  port: 1883
  readings_topic: "tele/snifferbuddy/+/+/SENSOR"
  lwt_topic: "tele/snifferbuddy/+/+/LWT"
  light_threshold: 500
database_paths:
  linux: "~/data/sniffer_data.sqlite"
  windows: "./data/sniffer_data.sqlite"
